### ISSUE TITLE
sendAndClose Method Had Stopped Working

### ISSUE THREAD

**Issue by barakhaim** [logzio/logzio-nodejs#17] opened 2016-08-04 13:39 UTC
Hi,

The sendAndClose Method  is not working any more.
When calling it the data is logged but the process doesn't end...
I had to revert back to my branch. 
It  seems that one of your recent changes broke this functionality.

--Barak

**Comment by gillyb** [comment] 2016-08-17 08:16
Hi @barakhaim, 
I'm very sorry about that. You're right - it was a bug caused by the previous pull request. I just committed a fix to it, and also bumped the version in npm

**Closed as completed by gillyb** 2016-08-17 08:16 UTC
